// appetizer id page
import Head from 'next/head';
import Navbar from '@/components/navbar/Navbar';
import Nav from '@/components/navbar/Nav';
import Detail from '@/components/appetizers/Detail';
import Footer from '@/components/misc/Footer';
// data
import appetizers from '@/data/appetizers';

function Details({ appetizer }) {
  return (
    <>
      <Head>
        <title>Appetizer Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="layout h-100">
        <div className=" container-fluid py-5 ">
          <Nav />
          <div className="container-fluid pb-5">
            <div className="row gx-4 ">
              <div className="col-lg-8">
                <Detail appetizers={appetizer} />
              </div>
              <div className="col-md-4">
                <h2 className="text-center fw-bold">{appetizer.name}</h2>
                <div className="d-flex justify-content-end">
                  <p className="lh-3 fs-6 m-1">{appetizer.description2}</p>
                </div>
              </div>
            </div>
            <div className="container mt-5 py-4 my-4">
              <hr className="hr w-25 mx-auto pt-5" />
              <div className="row">
                <div className="col-md-6">
                  <div className="container">
                    <h3 className="fw-bold me-5 text-center">Amenities</h3>
                  </div>
                  <div className=" ">{''}</div>
                </div>
                <div className="col-md-6">
                  <h3 className="fw-bold text-center">Locations</h3>
                  {''}
                  <div className="container d-flex justify-content-end fs-6 m-4"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const { params } = context;
  const { id } = params;

  // Find the appetizer with the matching id
  const appetizer = appetizers.find((appetizer) => appetizer.id === id);

  // Pass the appetizer as a prop
  return {
    props: {
      appetizer,
    },
  };
}

export default Details;
