import Head from "next/head";
//import Image from "next/image";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/misc/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>{"Lucy'bar & grill "}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='container layout h-100'>
      
      </div>
      <Footer />
    </>
  );
}
